site_name: Projectsveltos Documentation
copyright: Copyright Â© 2022 projectsveltos. All Rights Reserved.
site_description: 'Sveltos is a lightweight application designed to manage add-ons in hundreds of clusters. Projectsveltos extends functionality of Cluster API by providing a solution for managing the installation, configuration, upgrade, and deletion of kubernetes cluster add-ons using Helm charts and/or Kubernetes resource YAMLs. Projectsveltos supports multi-tenancy allowing platform admins to easily grant permissions to tenant admins.'
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html
- footnotes
- pymdownx.critic
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
- Projectsveltos: 'index.md'
- Use Cases:
  - Platform Administrators, Multicloud and Add-ons: 'use_cases/use_case_platform_admin_multicloud.md'
  - Platform Administrators and Multitenancy: 'use_cases/use_case_multitenancy.md'
  - Sveltos and Flux Integration: 'use_cases/use_case_flux_integration.md'
- Getting Started:
  - Installation:
    - Quick Start: 'getting_started/install/quick_start.md'
    - Install: 'getting_started/install/install.md'
  - Sveltosctl:
    - Sveltosctl: 'getting_started/sveltosctl/sveltosctl.md'
    - Visibility: 'getting_started/sveltosctl/visibility.md'
    - Tech support: 'getting_started/sveltosctl/techsupport.md'
    - Snapshot: 'getting_started/sveltosctl/snapshot.md'
- Register Clusters:
  - Register Cluster: 'register/register-cluster.md'
  - Register Management Cluster: 'register/register_management_cluster.md'
  - Register Claudie Powered Clusters: 'register/register_claudie_cluster.md'
  - Cluster Maintenance Window: 'register/cluster_maintenance_window.md'
- Deploy add-ons and applications:
  - Distribute Add-ons: 'addons/addons.md'
  - Deploy Helm Charts: 'addons/helm_charts.md'
  - Deploy YAML/JSON Kubernetes manifests: 'addons/raw_yaml.md'
  - Example Flux Sources: 'addons/example_flux_sources.md'
  - Deploy Kustomize Kubernetes manifests: 'addons/kustomize.md'
  - Add-on rollout strategy: 'addons/rolling_update_strategy.md'
  - ClusterProfile Example: 'addons/combining_all.md'
  - Deep dive into ClusterProfiles: 'addons/clusterprofile.md'
  - Deep dive into Profiles: 'addons/profile.md'
- Templating:
  - Introduction to Templates: 'template/intro_template.md'
  - Helm Charts and Resources as Templates: 'template/template_generic_examples.md'
  - Support for Carvel ytt: 'template/ytt_extension.md'
  - Support for Jsonnet: 'template/jsonnet_extension.md'
  - Example Mutlicluster Iteration and Deployment: 'template/example_multicluster_iteration_template.md'
  - Example Integration with Crossplane: 'template/crossplane.md'
  - Example Integration with External Secret Management: 'template/external_secret.md'
  - Example Integrate Sveltos with own controller: 'template/bring_your_own_controller.md'
- Resource Deployment Order:
  - Profile Resource Deployment Order: 'deployment_order/manifest_order.md'
  - Profile dependsOn field: 'deployment_order/depends_on.md'
  - Profile dependsOn and validateHealths: 'deployment_order/depends_on_with_health_checks.md'
  - Profile Tiers: 'deployment_order/tiers.md'
  - Scenario 'Event Framework and Resource Deployment': 'deployment_order/order_with_events.md'
- Features:
  - DryRun: 'features/dryrun.md'
  - Configuration Drift detection: 'features/configuration_drift.md'
  - Post Renderer Patches: 'features/post-renderer-patches.md'
  - Dynamic Cluster Management and Failover: 'features/set.md'
  - Rolling Upgrade Deployment, StatefulSet, DaemonSet: 'features/rolling_upgrade.md'
  - Cluster Classification: 'features/labels_management.md'
  - Multi-tenancy:
    - Full Isolation: 'features/multi-tenancy-full-isolation.md'
    - Tenants Sharing Clusters: 'features/multi-tenancy-sharing-cluster.md'
- Event Framework:
  - Automatically deploy Add-ons upon specific cluster events.: 'events/addon_event_deployment.md'
  - Templating: 'events/generators.md'
  - Example Managed Services: 'events/managed-services.md'
  - Example Service Event Trigger: 'events/example_service_event_trigger.md'
  - Example API Gateway with Contour: 'events/example_api_gateway_contour.md'
  - Example Cross-cluster Configuration: 'events/example_cross_cluster_configuration.md'
  - Example Loadbalancer: 'events/example_loadbalancer.md'
- Cluster Observability:
  - Notifications: 'observability/notifications.md'
  - Examples for Slack, Teams, Webex, Discord Notifications and k8s events: 'observability/example_addon_notification.md'
  - Example Slack Notification for Pods in crashloopbackoff: 'observability/example_crashloopbackoff_notification.md'
  - Example Deployment Health Notification: 'observability/example_deployment_health_notification.md'
  - Example Detect Degrade Certificates Notification: 'observability/example_degrade_certificate_notification.md'
  - Display Resources: 'observability/display_resources.md'
  - Cross-Resource Evaluation: 'observability/different_resources.md'
- Scalability:
  - Vertical Scaling: 'scalability/configuration.md'
  - Horizontal Scaling: 'scalability/sharding.md'
- Help and Tutorials:
  - Troubleshooting: 'help_and_tutorials/troubleshooting.md'
- Blogs and videos: 'blogs.md'
theme:
  features:
  - content.code.copy
  - search.share
  - navigation.footer
  - navigation.instant.progress
  - content.code.annotate
  name: material
  logo: assets/logo.png
  palette:
  - scheme: default
    primary: light blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: light blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
repo_url: https://github.com/projectsveltos
repo_name: projectsveltos
extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/projectsveltos
    name: squidfunk on Twitter
    link: https://join.slack.com/t/projectsveltos/shared_invite/zt-1hraownbr-W8NTs6LTimxLPB8Erj8Q6Q
  - icon: fontawesome/brands/github
    link: https://github.com/projectsveltos
  - icon: fontawesome/brands/medium
    link: https://medium.com/@gianluca.mardente
  - icon: fontawesome/brands/product-hunt
    link: https://www.producthunt.com/products/projectsveltos
extra_css:
- stylesheets/extra.css
plugins:
- search