apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: debuggingconfigurations.lib.projectsveltos.io
spec:
  group: lib.projectsveltos.io
  names:
    kind: DebuggingConfiguration
    listKind: DebuggingConfigurationList
    plural: debuggingconfigurations
    singular: debuggingconfiguration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DebuggingConfiguration is the Schema for the debuggingconfigurations
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DebuggingConfigurationSpec defines the desired state of DebuggingConfiguration
            properties:
              configuration:
                description: Configuration contains debugging configuration as granular
                  as per component.
                items:
                  description: ComponentConfiguration is the debugging configuration
                    to be applied to a Sveltos component.
                  properties:
                    component:
                      description: Component indicates which Sveltos component the
                        configuration applies to.
                      enum:
                      - AddonManager
                      - Classifier
                      - ClassifierAgent
                      - SveltosClusterManager
                      - DriftDetectionManager
                      - AccessManager
                      - HealthCheckManager
                      - EventManager
                      - ShardController
                      - UIBackend
                      type: string
                    logLevel:
                      description: 'LogLevel is the log severity above which logs
                        are sent to the stdout. [Default: Info]'
                      enum:
                      - LogLevelNotSet
                      - LogLevelInfo
                      - LogLevelDebug
                      - LogLevelVerbose
                      type: string
                  required:
                  - component
                  type: object
                type: array
                x-kubernetes-list-type: atomic
            type: object
        type: object
    served: true
    storage: false
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: DebuggingConfiguration is the Schema for the debuggingconfigurations
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DebuggingConfigurationSpec defines the desired state of DebuggingConfiguration
            properties:
              configuration:
                description: Configuration contains debugging configuration as granular
                  as per component.
                items:
                  description: ComponentConfiguration is the debugging configuration
                    to be applied to a Sveltos component.
                  properties:
                    component:
                      description: Component indicates which Sveltos component the
                        configuration applies to.
                      enum:
                      - AddonManager
                      - Classifier
                      - ClassifierAgent
                      - SveltosClusterManager
                      - DriftDetectionManager
                      - AccessManager
                      - HealthCheckManager
                      - EventManager
                      - ShardController
                      - UIBackend
                      type: string
                    logLevel:
                      description: 'LogLevel is the log severity above which logs
                        are sent to the stdout. [Default: Info]'
                      enum:
                      - LogLevelNotSet
                      - LogLevelInfo
                      - LogLevelDebug
                      - LogLevelVerbose
                      type: string
                  required:
                  - component
                  type: object
                type: array
                x-kubernetes-list-type: atomic
            type: object
        type: object
    served: true
    storage: true
