apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- access-manager.yaml
- addon-controller.yaml
- classifier.yaml
- event-manager.yaml
- healthcheck-manager.yaml
- mcp-server.yaml
- namespace.yaml
- register-mgmt-cluster.yaml
- shard-controller.yaml
- sveltoscluster-manager.yaml
- techsupport.yaml
components:
- ../components/crds